# Generated by Django 5.0.3 on 2024-03-23 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(verbose_name='Город')),
                ('state', models.CharField(verbose_name='Штат')),
                ('mail_zip', models.PositiveSmallIntegerField(verbose_name='Почтовый индекс')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('delivery_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_delivery', to='api.location', verbose_name='Место доставки груза')),
                ('pick_up_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_pick_up', to='api.location', verbose_name='Место подбора груза')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=5, unique=True, verbose_name='Уникальный номер автомобиля')),
                ('load_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='api.location', verbose_name='Текущая геопозиция')),
            ],
        ),
    ]
