# Generated by Django 5.0.3 on 2024-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240323_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mail_zip',
            field=models.CharField(max_length=5, unique=True, verbose_name='Почтовый индекс'),
        ),
    ]
